name: Semantic release

on:
  #push:
  #  branches:
  #    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # semantic release action from third party
      - uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          tag_format: 'v${version}'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          echo $RELEASE_VERSION
          echo $RELEASE_MAJOR
          echo $RELEASE_MINOR
          echo $RELEASE_PATCH
